name: Dastardly Scan Action

on:
  push:
    branches:
      - main

jobs:
  dastardly_scan:
    runs-on: ubuntu-latest

    inputs:
      target-url: ${{ github.event.inputs.target-url }}
      output-filename: ${{ github.event.inputs.output-filename }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Dastardly Scan
        uses: docker://Dockerfile
        with:
          args: >
            --env BURP_START_URL=${{ inputs.target-url }}
            --env BURP_REPORT_FILE_PATH=/github/workspace/${{ inputs.output-filename }}
