name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          registry-url: ghcr.io
          repository: your-username/my-html-app
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAC_GITHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ghcr.io/your-username/my-html-app .

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/your-username/my-html-app
