name: Build and Deploy HTML App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ghcr.io/your-username/my-html-app .

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.PAC_GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/your-username/my-html-app
