name: Build, Push, and Scan

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PAC_GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/my-html-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/my-html-app:latest

      - name: Set up Anchore CLI
        uses: anchore/setup-anchore-cli@v2
        with:
          version: latest

      - name: Analyze Docker Image with Anchore
        run: |
          anchore-cli image add ghcr.io/${{ github.repository_owner }}/my-html-app:latest
          anchore-cli analyze ghcr.io/${{ github.repository_owner }}/my-html-app:latest

  dastardly_scan:
    runs-on: ubuntu-latest

    needs: build_and_push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Dastardly Image
        run: docker pull portswigger/dastardly:latest

      - name: Run Dastardly Scan
        run: |
          docker run -v $(pwd):/target portswigger/dastardly:latest --target http://localhost:12121 --report /target/dastardly-report.xml

      - name: Upload Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: dastardly-report
          path: dastardly-report.xml
