# name: Build and Deploy

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Build and Push Docker image
#       run: |
#         echo "<html><body><h1>Hi,This my first application </h1></body></html>" > index.html

#         # Build and push Docker image
#         docker build -t ${{ github.repository_owner }}/my-html-app .
#         docker tag ${{ github.repository_owner }}/my-html-app ghcr.io/${{ github.repository_owner }}/my-html-app:latest
#         docker tag ${{ github.repository_owner }}/my-html-app ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest

#         # Login to GitHub Container Registry (GHCR)
#         echo "${{ secrets.PAC_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
#         docker push ghcr.io/${{ github.repository_owner }}/my-html-app:latest

#         # Login to Docker Hub
#         echo "${{ secrets.DOCKERHUB_USERNAME }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#         docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-html-app:latest
# .github/workflows/main.yml
name: Build and Run Locally

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-html-app .

    - name: Run Docker container locally
      run: docker run -p 11111:80 my-html-app
