name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAC_GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Adjust if your Dockerfile is in a different location
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-html-app:latest

  dastardly_scan:
    runs-on: ubuntu-latest

    needs: build_and_deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Dastardly Scan
        run: docker run ghcr.io/${{ github.repository_owner }}/my-html-app:latest
        env:
          BURP_START_URL: http://localhost:55555
          BURP_REPORT_FILE_PATH: /github/workspace/dastardly-report.xml
